export const iconAssets = {
  brandLogo: new URL('../../asset/brand-logo.png', import.meta.url).href,
  percent: new URL('../../asset/1.png', import.meta.url).href,
  cursor: new URL('../../asset/2.png', import.meta.url).href,
  eye: new URL('../../asset/3.png', import.meta.url).href,
  pencil: new URL('../../asset/4.png', import.meta.url).href,
  database: new URL('../../asset/5.png', import.meta.url).href,
  bars: new URL('../../asset/6.png', import.meta.url).href,
  megaphone: new URL('../../asset/7.png', import.meta.url).href,
  retrip: new URL('../../asset/8.png', import.meta.url).href,
  warning: new URL('../../asset/image-removebg-preview.png', import.meta.url).href,
  warningAmber: new URL('../../asset/image-removebg-preview (1).png', import.meta.url).href,
  bookmark: new URL('../../asset/image-removebg-preview (2).png', import.meta.url).href,
  exchange: new URL('../../asset/image-removebg-preview (3).png', import.meta.url).href,
  clock: new URL('../../asset/image-removebg-preview (4).png', import.meta.url).href,
  alert: new URL('../../asset/image-removebg-preview (5).png', import.meta.url).href,
  refreshPurple: new URL('../../asset/image-removebg-preview (6).png', import.meta.url).href,
  refreshTeal: new URL('../../asset/image-removebg-preview (7).png', import.meta.url).href,
  chat: new URL('../../asset/image-removebg-preview (8).png', import.meta.url).href,
  bell: new URL('../../asset/image-removebg-preview (9).png', import.meta.url).href,
  shieldCheck: new URL('../../asset/image-removebg-preview (10).png', import.meta.url).href,
  crowdAlert: new URL('../../asset/image-removebg-preview (11).png', import.meta.url).href,
  ribbon: new URL('../../asset/image-removebg-preview (12).png', import.meta.url).href,
  calendarPlus: new URL('../../asset/image-removebg-preview (13).png', import.meta.url).href,
  pin: new URL('../../asset/image-removebg-preview (14).png', import.meta.url).href,
  refreshBlue: new URL('../../asset/image-removebg-preview (15).png', import.meta.url).href,
  growth: new URL('../../asset/image-removebg-preview (16).png', import.meta.url).href,
  warningLine: new URL('../../asset/image-removebg-preview (17).png', import.meta.url).href,
  lock: new URL('../../asset/image-removebg-preview (18).png', import.meta.url).href,
  check: new URL('../../asset/image-removebg-preview (19).png', import.meta.url).href,
  culture: new URL('../../asset/image-removebg-preview (20).png', import.meta.url).href,
  cafe: new URL('../../asset/image-removebg-preview (21).png', import.meta.url).href,
  camera: new URL('../../asset/image-removebg-preview (22).png', import.meta.url).href,
  indoor: new URL('../../asset/image-removebg-preview (23).png', import.meta.url).href,
  food: new URL('../../asset/image-removebg-preview (24).png', import.meta.url).href,
  trendCoin: new URL('../../asset/image-removebg-preview (26).png', import.meta.url).href,
  clockBlue: new URL('../../asset/image-removebg-preview (27).png', import.meta.url).href,
  operator: new URL('../../asset/image-Photoroom (88).png', import.meta.url).href,
} as const;

export type IconAssetKey = keyof typeof iconAssets;
